Update ringct.md
alvinjoelsantos/promo-video pull request #13
Opened 2017-05-21 18:39 UTC by SamsungGalaxyPlayer

I tried to simplify the wording slightly. Includes a few grammar fixes. I also think we need a conclusion, so I added the heading for one.

2017-05-21 19:08 UTC, JollyMort requested changes

2017-05-21 19:08 UTC, JollyMort commented on ringct.md
> +The only difference is that you're comparing seemingly random numbers, but they must still will be the same on both sides of the transaction.
Can we reword to: The only difference is that you're comparing seemingly random numbers, but they can still be summed to check both sides of the transaction.

2017-05-21 19:08 UTC, JollyMort commented on ringct.md
> +The underlying cryptography guarantees that if both numbers are the same, then the amount being sent is the same as the amount of funds available.
and this one: The underlying cryptography guarantees that a check performed on commitments means that the amount being sent is the same as the amount of funds available.

2017-05-22 07:50 UTC, SamsungGalaxyPlayer commented
@JollyMort added your fixes

2017-05-22 07:52 UTC, merged